<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="title" content="Physiotherapy in Bogotá ✅ Telerehabilitation in Bogotá 🧿">
    <meta property="og:locale" content="es_ES" />
    <meta property="og:type" content="website" />
    <meta name="description"
        content="Physiotherapy Online Bogotá and Tele Rehabilitation in Bogotá ✅ Adriana Lucia Ramirez Bonilla ✅ Tele Rehabilitation Specialist in Bogotá">
    <meta name="keyword" content="Physiotherapy, Tele Rehabilitation, Pain, Consult, Neck Pain, Back Pain, Shoulder Pain, Hip Pain, 
                Knee Pain, physical conditioning, stretching, ankles, Sports Injuries">
    <meta property="og:url" content="https://fisioterapiaenbogota.com/" />
    <meta property="og:site_name" content="Physiotherapy in 🧿 Telerehabilitation in Bogotá ✅" />
    <meta property="og:image:width" content="621" />
    <meta property="og:image:height" content="603" />
    <meta name="twitter:card" content="summary_large_image" />
    <meta name="robots" content="index, follow" />

    <meta property="og:title" content="How Fysiopuntura was born">
    <meta property="og:url" content="http://fisioterapiaenbogota/physiotherapy">
    <meta property="og:description"
        content="On a physical level, the vulnerability generated by an injury stimulates in us an inner search process, that questions and transforms us.">
    <meta property="og:image" content="http://fisioterapiaenbogota.com/images/fisioterapia-en-bogota-colombia-1.jpg">
    <meta property="og:type" content="website">
    <meta property="og:site_name" content="Fysiopuntura">
    <meta property="og:locale" content="es_CO">


    <meta itemprop="name" content="How Fysiopuntura was born">
    <meta itemprop="url" content="http://fisioterapiaenbogota/physiotherapy">
    <meta itemprop="description"
        content="On a physical level, the vulnerability generated by an injury stimulates in us an inner search process, that questions and transforms us.">
    <meta itemprop="image" content="http://fisioterapiaenbogota.com/images/fisioterapia-en-bogota-colombia-1.jpg">


    <meta name="twitter:card" content="summary">
    <meta name="twitter:title" content="How Fysiopuntura was born">
    <meta name="twitter:url" content="http://fisioterapiaenbogota/physiotherapy">
    <meta name="twitter:description"
        content="On a physical level, the vulnerability generated by an injury stimulates in us an inner search process, that questions and transforms us.">
    <meta name="twitter:image" content="http://fisioterapiaenbogota.com/images/fisioterapia-en-bogota-colombia-1.jpg">
    <meta name="twitter:site" content="@fysiopuntura">

    <meta name="googlebot" content="index, follow, max-snippet:-1, max-image-preview:large, max-video-preview:-1" />
    <meta name="bingbot" content="index, follow, max-snippet:-1, max-image-preview:large, max-video-preview:-1" />
    <link rel="canonical" href="https://fisioterapiaenbogota.com/" />

    <link
        href="https://fonts.googleapis.com/css2?family=Courgette&family=Quicksand:wght@500;700&family=Raleway:ital,wght@0,200;0,400;1,200;1,400&display=swap"
        rel="stylesheet">

    <link rel="apple-touch-icon" sizes="57x57" href="{{ url('/') }}/images/favicon/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="{{ url('/') }}/images/favicon/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="{{ url('/') }}/images/favicon/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="{{ url('/') }}/images/favicon/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="{{ url('/') }}/images/favicon/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="{{ url('/') }}/images/favicon/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="{{ url('/') }}/images/favicon/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="{{ url('/') }}/images/favicon/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="{{ url('/') }}/images/favicon/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192" href="{{ url('/') }}/images/favicon/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="{{ url('/') }}/images/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="{{ url('/') }}/images/favicon/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="{{ url('/') }}/images/favicon/favicon-16x16.png">
    <link rel="manifest" href="{{ url('/') }}/images/favicon/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="{{ url('/') }}/images/favicon/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">

    <link rel="stylesheet" href="{{ url('/') }}/css/normalize.css">
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link rel="stylesheet" href="{{ url('/') }}/css/main.css">
    <link rel="stylesheet" href="{{ url('/') }}/css/responsive.css">
    <script src="js/fontawesome/fontawesome.js"></script>
    <link rel="stylesheet" href="{{ url('/') }}/css/swiper/swiper-bundle.min.css">
    <link rel="stylesheet" type="text/css" href="{{ url('/') }}/css/slick/slick.css" />
    <link rel="stylesheet" type="text/css" href="{{ url('/') }}/css/slick/slick-theme.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
    <link rel="stylesheet"
        href="https://rawcdn.githack.com/rafaelbotazini/floating-whatsapp/3d18b26d5c7d430a1ab0b664f8ca6b69014aed68/floating-wpp.min.css">
</head>

<body>
    <div id="app">
        @include('website.modulos.header_en')
        @include('website.modulos.menu_en')

        <section class="container-fluid d-flex justify-content-start nace-uno punto-partida">
            <div class="col-xs-6 col-md-6 align-self-center bg-white columna1">
                <div class="text-justify">@php echo $textos[0]->english; @endphp</div>
            </div>
        </section>

        <section class="container-fluid d-flex justify-content-end nace-dos">
            <div class="col-xs-6 col-md-6 align-self-center bg-white columna2">
                <div class="text-justify">@php echo $textos[1]->english; @endphp</div>
            </div>
        </section>

        <section class="container-fluid d-flex justify-content-start nace-tres">
            <div class="col-xs-6 col-md-6 align-self-center bg-white columna3">
                <div class="text-justify">@php echo $textos[2]->english; @endphp</div>
            </div>
        </section>

        <section class="container-fluid d-flex justify-content-end nace-cuatro">
            <div class="col-xs-6 col-md-6 align-self-center bg-white columna4">
                <div class="text-justify">@php echo $textos[3]->english; @endphp</div>
            </div>
        </section>

        <section class="container-fluid d-flex justify-content-start nace-cinco">
            <div class="col-xs-6 col-md-6 align-self-center bg-white columna5">
                <div class="text-justify">@php echo $textos[4]->english; @endphp</div>
            </div>
        </section>
    </div>

    @include('website.paginas.seccion9_en')

    @include('website.paginas.seccion7_en')

    @include('website.paginas.seccion8_en')

    @include('website.modulos.footer_en')

    <div id="WAButton"></div>
    <span class="ir-arriba"><i class="fa fa-arrow-up" aria-hidden="true"></i></span>


    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script src="{{ asset('js/app.js') }}"></script>
    <script type="text/javascript" src="//code.jquery.com/jquery-1.11.0.min.js"></script>
    <script type="text/javascript" src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
    <script type="text/javascript" src="{{ url('/') }}/js/slick/slick.min.js"></script>
    <script src="{{ url('/') }}/js/swiper/swiper-bundle.min.js"></script>
    <script src="{{ url('/') }}/plugins/waypoints/jquery.waypoints.min.js"></script>
    <script type="text/javascript"
        src="https://rawcdn.githack.com/rafaelbotazini/floating-whatsapp/3d18b26d5c7d430a1ab0b664f8ca6b69014aed68/floating-wpp.min.js">
    <script type="text/javascript" src="{{ url('/') }}/js/main.js"></script>
    <script type="text/javascript" src="{{ url('/') }}/js/botonws.js"></script>

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-169704393-1"></script>
    <script>
        window.dataLayer = window.dataLayer || [];

        function gtag() {
            dataLayer.push(arguments);
        }
        gtag('js', new Date());

        gtag('config', 'UA-169704393-1');

    </script>
</body>

</html>
